include:
  - compose-base.yml

services:
  app:
    image: backend 
    restart: always
    env_file: env_app_docker
    depends_on:
      - mongo 
    ports:
      - "8080:8080"
    networks:
      - backend  

